name: Question
description: Ask a question about usage or implementation
title: "[Question]: "
labels: ["question", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation and existing issues first.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Usage - How to use the project
        - Configuration - Setup and configuration
        - Performance - Performance related questions
        - Integration - Integrating with other systems
        - Development - Contributing or extending the project
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your use case
      placeholder: |
        - What are you trying to achieve?
        - What have you already tried?
        - Any relevant environment details?

  - type: textarea
    id: research
    attributes:
      label: Research Done
      description: What documentation or resources have you already checked?
      placeholder: |
        - [ ] README.md
        - [ ] Documentation in docs/
        - [ ] Existing issues
        - [ ] Stack Overflow
        - [ ] Other resources: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Code examples, error messages, or other relevant details...
